version: "3.9"
services:

  redis:
    container_name: redis_db
    image: redis:latest
    networks:
      - local

  postgres_post:
    image: postgres:latest
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: post_service
      POSTGRES_PASSWORD: '22848'
    networks:
      - local

  clickhouse:
    image: 'bitnami/clickhouse:latest'
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - local

  kafka:
    image: 'bitnami/kafka:3.6'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - local


  main_service:
    build:
      context: .
      dockerfile: main_service/Dockerfile
    depends_on:
      - redis
      - post_service
    restart: on-failure:10
    ports:
      - 8000:8000
    networks:
      - local

  post_service:
    build:
      context: .
      dockerfile: post_service/Dockerfile
    depends_on:
      - postgres_post
    restart: on-failure:10
    networks:
      - local

  stats_service:
    build:
      context: .
      dockerfile: stats_service/Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - clickhouse
      - kafka
    networks:
      - local
    restart: on-failure:10

networks:
  local:
    driver: bridge
