version: "3.9"
services:
  redis:
    container_name: redis_db
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - local
  main_service:
    build: .
    depends_on:
      - redis
    ports:
      - 8000:8000
    networks:
      - local
networks:
  local:
    driver: bridge
